# Generated by Django 4.2.3 on 2024-11-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_alter_companyjobs_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyjobs',
            options={'verbose_name': 'Company Job', 'verbose_name_plural': 'Company Jobs'},
        ),
    ]
