# Generated by Django 4.2.3 on 2024-11-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_company_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.companyjobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.aspirants')),
            ],
        ),
    ]
